# This file was *autogenerated* from the file means.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1)
def arithmean(*numbers):
    """Arithmetical mean"""
    return sum(numbers) / len(numbers)


def geomean(*numbers):
    """Geometric mean"""
    product = _sage_const_1 
    for n in numbers:
        product *= n
    return pow(product, _sage_const_1  / len(numbers))


def harmonicmean(*numbers):
    """Harmonic mean"""
    reciprocals = [_sage_const_1  / n for n in numbers]
    return len(numbers) / sum(reciprocals)


def quadraticmean(*numbers):
    """Quadratic mean"""
    squares = [n ** _sage_const_2  for n in numbers]
    return sqrt(sum(numbers) / len(numbers))


def quadratic_harmonicmean(*numbers):
    """Quadratic mean"""
    square_reciprocals = [_sage_const_1  / n ** _sage_const_2  for n in numbers]
    return len(numbers) / sum(square_reciprocals) ** _sage_const_2 


print(arithmean(_sage_const_1 , _sage_const_2 ))
print(geomean(_sage_const_1 , _sage_const_2 ))
print(harmonicmean(_sage_const_1 , _sage_const_2 ))
print(quadraticmean(_sage_const_1 , _sage_const_2 ))
print(quadratic_harmonicmean(_sage_const_1 , _sage_const_2 ))

